before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: W6bHqalbXE0Qkv2+e04QWprAxDKamrSo8mWyPoRXfPMPxZdc9+ypsAq6BuxS5WoFZRUXA4mH5zcSql6ehMT27fHaf2yQVfRds0adY2JtrPAkbOPNbUnlkV7z9wedsEgnInG4JcVDRw2xULh82GShs9c9AePgipPJLQNKiqhnlDbb4fXtC63qvPE67VSVlx6a/wZi19Hw8AAVjuqUIZAy5z3X1M6LggbvkeJZVLM/3ltoI+Eqaw+Hxdh7qwBLYZQ3p+EF0GFjFrYg9fwLXIFWltoXUuKy3MOkIy4vWJ9Z5JQUAaRJbyPuoMYkycJ9ebYNYBcH6JFlnIdyT6kiVl2kdmRfCcgDvoVBmqT6j1XxeaxW7yDCgIYgWC/1C75aBq24YsyzbsvJG1pDywiSSfRSqdqjqP/JRKOHj5862NzevtX0Rmgd6DwePWu/6Vk4LdS1TDOQABUvrZvWCI9d5hWVhogAkZ0vPtfBKiPMF1CMJNMu7swihBRUDRHgPhNuE7jPohQ8X8oxlaLd2AmdUm+PnXZAGNsdGQtbvgodOFEmHNiKlds04tZcX9SHqUvI214J1FfGiiYnHdzrYs0ePaEyLU/Tb6n2OnbnPn/v/mLjKm0cuTV9Myo7NyNgscCNmsQ9uorfecNp5l/yw4hu2nr5NA6pxClrv5t/ZRqUFhuCmjM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
